apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    name: pod-3
spec:
  nodeSelector: 
    kubernetes.io/hostname: k8s-node1
  containers:
  - name: pod-3
    image: tmkube/init
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
